-- Create and seed products table for SQL Server
SET NOCOUNT ON;

-- 1) Create database if it does not exist
IF DB_ID(N'ApniDukaanProducts') IS NULL
BEGIN
	CREATE DATABASE ApniDukaanProducts;
END
GO

-- Use the database
USE [ApniDukaanProducts];
GO

-- 2) Create products table if it does not exist
IF NOT EXISTS (
	SELECT 1 FROM sys.tables t
	JOIN sys.schemas s ON t.schema_id = s.schema_id
	WHERE t.name = N'products' AND s.name = N'dbo'
)
BEGIN
	CREATE TABLE dbo.products
	(
		ProductID UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_products_ProductID DEFAULT NEWID(),
		ProductName VARCHAR(50) NOT NULL,
		Category VARCHAR(50) NULL,
		UnitPrice DECIMAL(10,2) NULL,
		QuantityInStock INT NULL,
		CONSTRAINT PK_products PRIMARY KEY (ProductID)
	);
END
GO

-- 3) Insert sample rows (ProductID will be generated by DEFAULT NEWID())
INSERT INTO dbo.products (ProductName, Category, UnitPrice, QuantityInStock)
VALUES
	('Apple iPhone 15 Pro Max', 'Electronics', 1299.99, 50),
	('Samsung Foldable Smart Phone 2', 'Electronics', 1499.99, 100),
	('Ergonomic Office Chair', 'Furniture', 249.99, 25),
	('Coffee Table with Storage', 'Furniture', 179.99, 30),
	('Samsung QLED 75 inch', 'Electronics', 1999.99, 20),
	('Running Shoes', 'Furniture', 49.99, 75),
	('Anti-Theft Laptop Backpack', 'Accessories', 59.99, 60),
	('LG OLED 65 inch', 'Electronics', 1499.99, 15),
	('Modern Dining Table', 'Furniture', 699.99, 10),
	('PlayStation 5', 'Electronics', 499.99, 40),
	('Executive Office Desk', 'Furniture', 299.99, 18),
	('Breville Smart Blender', 'HomeAppliances', 129.99, 50);
GO

-- Verification: select inserted rows
SELECT TOP (12) * FROM dbo.products ORDER BY ProductName;
GO
